---
apiVersion: kubescheduling.k8s.io/v1beta1
kind: Cost
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: regular-task-cost
spec:
  resources:
    cpu: 3
    memory: 5
    nvidia.com/gpu: 1
    storage: 50
    priority: 3
---
apiVersion: kubescheduling.k8s.io/v1beta1
kind: Cost
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: high-priority-task-cost
spec:
  resources:
    cpu: 0.3
    memory: 0.005
    nvidia.com/gpu: 0
    storage: 80
    priority: 5
